#!/usr/bin/perl -n
#while(<>){/\[.*?\] \[.*?\] \[.*?\] (.*), referer:/;print qq[$1\n];}
#while(<>){/(\[.*?\] ){1,3}(.*?), referer:/; print qq[$2\n];}
print if /AndroidRuntime|System\.|com.wandoujia.p4|wdj\.|HTTP/;
