#!/usr/bin/perl -n
#while(<>){/\[.*?\] \[.*?\] \[.*?\] (.*), referer:/;print qq[$1\n];}
#while(<>){/(\[.*?\] ){1,3}(.*?), referer:/; print qq[$2\n];}
s/^(\[.*?\] ){3,4}//; s/, referer.*//; 
$_="\n" if /Use of uninitialized value/;
print;
