#!/bin/bash

url=svn://svn/SWM/trunk
user=$USER

TEMP=`getopt -o u:l: --long user,url -n 'mlog' -- "$@"`
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$TEMP"

while true ; do
    case "$1" in
        -u|--user) user=$2; shift 2;;
         -l|--url) url=$2; shift 2;;
               --) shift ; break ;;
                *) echo "Internal error! $1" ; exit 1 ;;
    esac
done

offset="last monday"
if [ ! -z "$1" ]; then
    offset="$1 days ago"
fi

echo "SVN log for $user, $offset"

#start_date=$(date +%Y-%m-%d -d "$offset days ago")
start_date=$(date +%Y-%m-%d -d "$offset")
end_date=$(date +%Y-%m-%d)

for r in $(svn log $url -r {$start_date}:{$end_date}| grep $user| cut -d'|' -f1);
do 
    svn log $url -$r -v ; 
done
